import imaplib, json
creds = json.load(open(r"C:\Users\yasir\.claude-tools\azwebcorp-creds.json"))
M = imaplib.IMAP4_SSL("imap.secureserver.net", 993)
M.login(creds["mail_user"], creds["mail_password"])
typ, sel = M.select("INBOX", readonly=True)
print("EXISTS:", sel)
typ, data = M.uid("search", None, "ALL")
uids = data[0].split()
print("highest inbox uid:", uids[-1].decode() if uids else None)
print("count:", len(uids))
M.logout()
