#!/usr/bin/env python3
"""
Generate FAQPage JSON-LD for each landing page from its VISIBLE FAQ markup.

Google requires the structured data to match the text rendered on the page.
Rather than hand-transcribing the Q&As (which drifts the moment copy is
edited), this reads the <h3>/<p> pairs that follow the "FAQ" <h2> and emits
schema straight from them. Re-runnable: an existing generated block is
replaced, so editing page copy and re-running keeps schema in sync.
"""

import html
import json
import re
import sys
from pathlib import Path

PAGES_DIR = Path(__file__).resolve().parent.parent / "landing-pages"

MARKER = "<!-- FAQPage schema: generated by scripts/add_faq_schema.py -->"
# Matches a previously generated block, plus the blank lines around it, so a
# re-run restores the exact pre-injection state and stays byte-idempotent.
GENERATED_RE = re.compile(
    r"\n*" + re.escape(MARKER) + r".*?</script>\n*", re.DOTALL
)


def visible_text(fragment: str) -> str:
    """Strip inline tags and decode entities -> the text a user actually reads."""
    text = re.sub(r"<[^>]+>", "", fragment)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def extract_faqs(source: str):
    """Return [(question, answer)] from the FAQ section, in document order."""
    faq_h2 = re.search(r"<h2>\s*FAQ\s*</h2>", source, re.IGNORECASE)
    if not faq_h2:
        return []

    # The FAQ section runs to the next <h2> (if any), else to </body>.
    rest = source[faq_h2.end():]
    next_h2 = re.search(r"<h2[\s>]", rest)
    section = rest[: next_h2.start()] if next_h2 else rest

    pairs = re.findall(
        r"<h3>(.*?)</h3>\s*<p>(.*?)</p>", section, re.DOTALL | re.IGNORECASE
    )
    return [(visible_text(q), visible_text(a)) for q, a in pairs]


def build_block(faqs) -> str:
    payload = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": q,
                "acceptedAnswer": {"@type": "Answer", "text": a},
            }
            for q, a in faqs
        ],
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return f'{MARKER}\n<script type="application/ld+json">\n{body}\n</script>\n'


def process(path: Path) -> str:
    source = path.read_text(encoding="utf-8")
    source = GENERATED_RE.sub("\n\n", source)  # drop stale generated block first

    faqs = extract_faqs(source)
    if not faqs:
        path.write_text(source, encoding="utf-8")
        return f"skip   {path.name}: no FAQ section"

    if '"@type": "FAQPage"' in source:
        return f"skip   {path.name}: hand-written FAQPage already present"

    if "<body>" not in source:
        return f"WARN   {path.name}: no <body> tag, cannot place block"

    updated = source.replace("<body>", build_block(faqs) + "\n<body>", 1)
    path.write_text(updated, encoding="utf-8")
    return f"ok     {path.name}: {len(faqs)} Q&A"


def main() -> int:
    files = sorted(PAGES_DIR.glob("*.html"))
    if not files:
        print(f"No HTML files found in {PAGES_DIR}", file=sys.stderr)
        return 1
    for path in files:
        print(process(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
